### ISSUE TITLE
iniciando o projeto

### ISSUE THREAD

**Issue by marcelomodesto** [ime-usp-br/monitoria#1]

**Comment by ayrtonnotrya** [comment]
[6913eb4](https://github.com/ime-usp-br/monitoria/commit/6913eb44d8b8fc072fdf5deeda949de6931a6e4e)

**Comment by marcelomodesto** [comment]
- [x] criar o projeto com o laravel
- [x] adicionar biblioteca senha única
- [x] adicionar biblioteca usp theme
- [ ] criar ambiente de homologação
