### ISSUE TITLE
Criação declaração de monitoria

### ISSUE THREAD

**Issue by marcelomodesto** [ime-usp-br/monitoria#16]
Criar o relatório "declaração" de monitoria, em formato pdf, com base no modelo enviado.
O relatório é do período letivo concluído e para alunos monitores com frequência regular (confirmar essa restrição).

**Comment by ayrtonnotrya** [comment]
Foi atendido no commit 9e1704d64c48fa9b48f04ff2329c9fa5b2ef61f9

**Comment by marcelomodesto** [comment]
@ayrtonnotrya  Há dois tipos de declaração: 
a) declaração enquanto o monitor está em atividade;
b) certificado para quando a monitoria foi encerrada.
