### ISSUE TITLE
Implementar auto avaliação do monitor

### ISSUE THREAD

**Issue by marcelomodesto** [ime-usp-br/monitoria#27]
No final da monitoria o monitor deve submeter um relatório de atividades e uma auto avaliação, cujo link é enviado pelo e-mail do sistema.

**Comment by ayrtonnotrya** [comment]
Foi tendido nos commits 4667653065ff1728b66b94dfd054ff56204ef740 6b2ebaee4786f3c5e53dd9b87c108ccf60416d28 1149253bdb8079f7bfb6bcfcef43ab1e62c5e767
